version: 2.1

orbs:
  go: circleci/go@1.7.2
  tf: circleci/terraform@3.2.0

executors:
  go1193:
    docker:
      - image: cimg/go:1.19.3
  ubuntu2204:
    machine:
      image: ubuntu-2204:2022.10.2

jobs:
  test:
    executor: ubuntu2204
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Spin up test dependencies
          command: docker-compose up -d
      - go/install:
          version: '1.19.3'
      - run:
          name: Install dependencies
          command: go mod tidy
      - run:
          name: Setup and build local binary
          command: make init
          environment:
            OS: linux
            ARCH: amd64
      - run:
          name: Wait for mock server (8080)
          command: |
            # Docker Compose needs to pull the images;
            # Prism may take quite some time to initialize

            N=20
            while [ $N -gt 0 ]
            do
              if $(curl -s --fail -H "Circle-Token: fooBar" -o /dev/null http://127.0.0.1:8080/api/v2/webhook\?scope-id\=123e4567-e89b-12d3-a456-426614174000\&scope-type\=project); then
                echo "Connected!"
                exit 0
              fi
              echo "Not connected; retrying"
              N=$(( $N - 1 ))
              sleep 2
            done
            exit 1
      - run:
          name: Run acceptance tests
          command: make testacc

  docs:
    executor: go1193
    resource_class: medium
    steps:
      - checkout
      - tf/install:
          terraform_version: '1.3.7'
      - run:
          name: Install dependencies
          command: go mod tidy
      - run: make binary
      - run: make docs
      - run: git status

workflows:
  on-commit:
    jobs:
      - test
      - docs
